window.twoHourExpansionQuestionBank = {
  math8: [
    {
      prompt: "A taxi charges a $4 start fee plus $2.25 per mile. A student has $31. What inequality shows the miles m the student can afford?",
      standard: "Grade 8 Math: Linear Relationships",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["4 + 2.25m <= 31", "4m + 2.25 <= 31", "31 + 2.25m <= 4", "2.25m - 4 >= 31"],
      correct: 0,
      skill: "多步文字题",
      explanation: "The total cost is the start fee plus the per-mile cost. The cost must be less than or equal to the money available.",
      coachHints: ["Which part is fixed before any miles?", "What expression represents the total cost after m miles?"],
    },
    {
      prompt: "A line passes through (2, 9) and (6, 1). What does its slope tell you about the relationship?",
      standard: "Grade 8 Math: Slope and Rate of Change",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["y decreases by 2 for each 1 increase in x", "y increases by 2 for each 1 increase in x", "x decreases by 8 for each 4 increase in y", "The relationship has no rate of change"],
      correct: 0,
      skill: "斜率概念",
      explanation: "The slope is (1 - 9) / (6 - 2) = -8/4 = -2, so y decreases by 2 each time x increases by 1.",
      coachHints: ["Use change in y over change in x.", "What does a negative slope mean in words?"],
    },
    {
      prompt: "A scatterplot shows study time and quiz score with points rising from left to right but not forming a perfect line. Which statement is best?",
      standard: "Grade 8 Math: Data and Trend Lines",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["There is a positive association, but predictions may not be exact", "There is no association because the points are not perfectly straight", "Studying causes every score to be 100", "The y-values must all be equal"],
      correct: 0,
      skill: "数据图表",
      explanation: "A rising pattern shows positive association. Because the points vary, a trend can support estimates but not exact guarantees.",
      coachHints: ["What overall direction do the points move?", "Does association mean every point must fit perfectly?"],
    },
    {
      prompt: "A water tank starts with 18 gallons and drains at 1.5 gallons per minute. Which equation shows the gallons g after m minutes?",
      standard: "Grade 8 Math: Linear Modeling",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["g = 18 - 1.5m", "g = 1.5m - 18", "g = 18m - 1.5", "g = 19.5m"],
      correct: 0,
      skill: "比例关系",
      explanation: "The starting amount is 18, and draining means the amount decreases by 1.5 for each minute.",
      coachHints: ["What is the initial value before time passes?", "Should draining make the expression add or subtract?"],
    },
    {
      prompt: "A student says the slope from (1, 4) to (5, 12) is 1/2 because 5 - 1 = 4 and 12 - 4 = 8. What is the error?",
      standard: "Grade 8 Math: Error Analysis",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The student reversed rise and run; the slope is 8/4 = 2", "The student should add all coordinates", "The slope is always the first y-value", "The points cannot have a slope"],
      correct: 0,
      skill: "斜率概念",
      explanation: "Slope is change in y divided by change in x. The change in y is 8 and the change in x is 4.",
      coachHints: ["Which change goes on top in slope?", "What are the rise and run between the two points?"],
    },
    {
      prompt: "The equation 3x + 7 = 31 models a word problem. Which situation could match it?",
      standard: "Grade 8 Math: Equations from Context",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Three equal tickets plus a $7 fee cost $31", "Seven equal tickets plus a $3 fee cost $31", "Three tickets cost $7 total", "A $31 fee is added to 3 tickets"],
      correct: 0,
      skill: "多步文字题",
      explanation: "The expression 3x means three equal unknown costs, and +7 means an additional fixed fee.",
      coachHints: ["What does 3x represent in a story?", "What does the +7 have to be if it is not repeated?"],
    },
    {
      prompt: "A table shows x-values increasing by 2 while y-values increase by 10. What should a student write to justify the rate of change?",
      standard: "Grade 8 Math: Rate of Change",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["For every 1 increase in x, y increases by 5", "For every 1 increase in x, y increases by 10", "The rate cannot be found from a table", "The y-intercept must be 10"],
      correct: 0,
      skill: "斜率概念",
      explanation: "The rate is change in y divided by change in x. Since 10 divided by 2 is 5, y increases by 5 for each 1 x.",
      coachHints: ["What is change in y?", "Divide the y-change by the x-change, then write it in words."],
    },
    {
      prompt: "A student claims y = 6x is not proportional because the graph is steep. What is the best response?",
      standard: "Grade 8 Math: Proportional Relationships",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["It is proportional because it has the form y = kx and passes through the origin", "It is not proportional because 6 is too large", "Steep graphs are never proportional", "Only horizontal lines are proportional"],
      correct: 0,
      skill: "比例关系",
      explanation: "A proportional relationship can be written as y = kx and has a graph through the origin. The steepness only shows the constant of proportionality.",
      coachHints: ["What form shows a proportional relationship?", "Does steepness change whether the graph passes through the origin?"],
    },
    {
      prompt: "A box plot has a much longer right whisker than left whisker. What interpretation is most reasonable?",
      standard: "Grade 8 Math: Data Distribution",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The upper values are more spread out", "The median must be zero", "All values are the same", "The lower quartile is the maximum"],
      correct: 0,
      skill: "数据图表",
      explanation: "A longer whisker means the data in that direction are more spread out. The right whisker describes spread among higher values.",
      coachHints: ["What does a whisker show on a box plot?", "Which side has more spread?"],
    },
  ],
  rla8: [
    {
      prompt: "An article opens with a student's story, then gives school-wide survey data. Why might the author use both kinds of evidence?",
      standard: "Grade 8 RLA: Author's Purpose and Evidence",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The story builds interest while the data broadens support", "The data proves the story is fictional", "The story replaces the need for evidence", "The survey changes the topic completely"],
      correct: 0,
      skill: "证据比较",
      explanation: "A personal example can engage readers, while broader data helps show that the issue is not limited to one person.",
      coachHints: ["What does the story do emotionally?", "What does survey data add that one story cannot prove?"],
    },
    {
      prompt: "A poem repeats the phrase 'still I waited' after each setback. What effect does the repetition most likely create?",
      standard: "Grade 8 RLA: Literary Devices",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["It emphasizes patience and persistence", "It proves the speaker changed topics", "It makes the setting disappear", "It shows the poem has no theme"],
      correct: 0,
      skill: "主题与主张",
      explanation: "Repeated words often highlight an important idea. Here, repeated waiting after setbacks supports persistence.",
      coachHints: ["Which idea appears again and again?", "How does each setback change the meaning of waiting?"],
    },
    {
      prompt: "Two texts agree that school lunches should improve, but one focuses on cost and the other on health. What comparison should a strong response make?",
      standard: "Grade 8 RLA: Paired Passage Analysis",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["They share a general claim but use different reasons", "They have opposite topics", "Only the longer text has evidence", "The texts cannot be compared"],
      correct: 0,
      skill: "证据比较",
      explanation: "A strong comparison notices both similarity and difference: the shared position and the different reasoning behind it.",
      coachHints: ["What do the two texts agree about?", "What reason does each text use to support the shared claim?"],
    },
    {
      prompt: "A student claims a character is selfish because she leaves the room. Which evidence would best test whether that claim is too simple?",
      standard: "Grade 8 RLA: Inference and Evidence",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["A later detail shows she left to get help for someone", "The room had a window", "The paragraph is short", "The story is written in past tense"],
      correct: 0,
      skill: "证据推理",
      explanation: "A strong inference must fit all important evidence. Leaving to help someone changes the meaning of the action.",
      coachHints: ["What evidence would change how we interpret leaving?", "Does one action always prove a motive by itself?"],
    },
    {
      prompt: "Which sentence would best summarize a paragraph about how one invention changed communication but also created new problems?",
      standard: "Grade 8 RLA: Summary",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The invention improved communication while creating challenges people had to solve", "The invention was invented by an inventor", "Communication is a word in the paragraph", "Every invention is always harmful"],
      correct: 0,
      skill: "主题与主张",
      explanation: "A good summary includes the central idea and both sides of the paragraph's development without extra unsupported claims.",
      coachHints: ["What are the two main effects described?", "Which choice is broad enough but still specific?"],
    },
    {
      prompt: "An author uses the phrase 'the hallway swallowed the sound.' What should a reader infer from this figurative language?",
      standard: "Grade 8 RLA: Figurative Language",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The hallway seemed quiet and empty enough to absorb noise", "The hallway literally ate something", "The sound became louder", "The author stopped using imagery"],
      correct: 0,
      skill: "词汇语境",
      explanation: "Figurative language should be interpreted by effect and context, not as a literal event.",
      coachHints: ["Is 'swallowed' literal here?", "What feeling does the phrase create about the hallway?"],
    },
    {
      prompt: "A response says, 'The theme is courage,' but gives no evidence. Which revision best turns it into a strong constructed response?",
      standard: "Grade 8 RLA: Constructed Response",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The theme is courage because the character speaks up even after others laugh at her", "The theme is courage because courage is good", "The story is about a character", "I liked the ending"],
      correct: 0,
      skill: "短文写作",
      explanation: "A strong response states the idea and supports it with a specific action from the text.",
      coachHints: ["Where is the text evidence?", "Does the sentence explain why the evidence proves the theme?"],
    },
    {
      prompt: "A passage describes a town as 'polished on the outside but restless underneath.' What contrast should a reader explain?",
      standard: "Grade 8 RLA: Theme and Mood",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The town appears orderly but has hidden tension", "The town has no conflict", "The outside of the town is made of metal", "The narrator dislikes all towns"],
      correct: 0,
      skill: "主题与主张",
      explanation: "The phrase contrasts appearance with hidden feeling. 'Polished' suggests order, while 'restless' suggests tension.",
      coachHints: ["What does polished suggest?", "What does restless suggest that is different?"],
    },
    {
      prompt: "Which evidence best supports the idea that the narrator is unreliable?",
      standard: "Grade 8 RLA: Point of View",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The narrator admits forgetting key events but insists the memory is perfect", "The narrator describes the weather", "The story has dialogue", "The narrator uses first person"],
      correct: 0,
      skill: "证据推理",
      explanation: "An unreliable narrator gives reasons to question the account. Forgetting events while claiming perfect memory creates that doubt.",
      coachHints: ["What detail makes the narrator hard to trust?", "Is first person alone enough to prove unreliability?"],
    },
  ],
  science8: [
    {
      prompt: "A student tests whether salt affects boiling point. Trial A uses 200 mL water and no salt; Trial B uses 300 mL water and salt. What should be improved?",
      standard: "Grade 8 Science: Experimental Design",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Keep the water amount the same so only salt changes", "Use different thermometers in each trial", "Stop measuring temperature", "Change the question after collecting data"],
      correct: 0,
      skill: "变量控制",
      explanation: "A controlled experiment should change one independent variable. Changing both salt and water amount makes the cause unclear.",
      coachHints: ["Which variables changed between Trial A and Trial B?", "How many variables should change in a fair test?"],
    },
    {
      prompt: "A table shows a cart's speed increasing each second while force stays constant. Which explanation best connects the data to motion?",
      standard: "Grade 8 Science: Force and Motion",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The constant unbalanced force is causing acceleration", "The cart is not moving because force is constant", "Speed cannot be measured over time", "The data only shows mass"],
      correct: 0,
      skill: "数据解释",
      explanation: "Increasing speed over time means acceleration. A constant unbalanced force can produce that acceleration.",
      coachHints: ["What does speed increasing over time mean?", "Is a constant force always the same as no force?"],
    },
    {
      prompt: "A model shows the Sun, Earth, and Moon aligned with Earth in the middle. Which event can this model explain?",
      standard: "Grade 8 Science: Earth and Space",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["A lunar eclipse", "A change in seasons", "Ocean salinity", "Plate boundaries"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "When Earth is between the Sun and Moon, Earth's shadow can fall on the Moon, causing a lunar eclipse.",
      coachHints: ["Which object is in the middle?", "Whose shadow would fall on the Moon?"],
    },
    {
      prompt: "A student concludes that a metal ball is denser than a wooden ball because both have the same volume but the metal ball has more mass. Is the reasoning valid?",
      standard: "Grade 8 Science: Density",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Yes, with equal volume, greater mass means greater density", "No, density only depends on color", "No, equal volume means equal density", "Yes, but only if both balls float"],
      correct: 0,
      skill: "科学词汇",
      explanation: "Density is mass divided by volume. If volume is the same, the object with greater mass has greater density.",
      coachHints: ["What is the formula idea for density?", "If the denominator is the same, what happens when mass is larger?"],
    },
    {
      prompt: "A graph of temperature during a phase change stays flat while heat is added. What does the flat section show?",
      standard: "Grade 8 Science: Matter and Energy",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Energy is being used to change state rather than raise temperature", "No energy is entering the system", "The thermometer stopped working for sure", "The substance disappeared"],
      correct: 0,
      skill: "数据解释",
      explanation: "During a phase change, added energy changes particle arrangement, so temperature can remain constant for a period.",
      coachHints: ["Is heat still being added during the flat part?", "What else can energy do besides raise temperature?"],
    },
    {
      prompt: "A student says a heavier object must fall faster in every situation. Which evidence would best challenge that claim?",
      standard: "Grade 8 Science: Force and Motion",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Data showing two objects with different masses falling at the same rate when air resistance is minimized", "A picture of a heavy object", "A list of object colors", "A graph with no labels"],
      correct: 0,
      skill: "数据解释",
      explanation: "A claim should be tested with controlled evidence. Data under minimized air resistance can challenge the idea that mass alone controls fall rate.",
      coachHints: ["What kind of evidence directly tests falling rate?", "What variable needs to be controlled or minimized?"],
    },
    {
      prompt: "A student writes that the conclusion is valid because 'the numbers changed.' What should a stronger scientific explanation include?",
      standard: "Grade 8 Science: Evidence-Based Reasoning",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["A specific data trend and how it supports the claim", "A longer title", "A statement that data is always correct", "A new unrelated variable"],
      correct: 0,
      skill: "实验设计",
      explanation: "Scientific reasoning should connect a claim to specific evidence and explain why the evidence supports it.",
      coachHints: ["Which numbers changed, and in what direction?", "How does that trend support the claim?"],
    },
    {
      prompt: "A diagram shows warm air rising and cool air sinking. Which process does this best model?",
      standard: "Grade 8 Science: Weather and Energy Transfer",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["Convection", "Radiation only", "Condensation only", "Genetic variation"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "Convection is heat transfer by movement of fluid, including air. Warm air rises and cooler air sinks in a cycle.",
      coachHints: ["What is moving in the diagram?", "Which heat transfer involves moving fluid?"],
    },
    {
      prompt: "A mineral sample scratches glass and has a repeating crystal pattern. Which properties are being used for identification?",
      standard: "Grade 8 Science: Earth Materials",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["Hardness and crystal structure", "Mass and weather", "Color only", "Temperature and gravity"],
      correct: 0,
      skill: "科学词汇",
      explanation: "Scratching glass tests hardness, and a repeating pattern describes crystal structure.",
      coachHints: ["What property is tested by scratching?", "What does a repeating pattern describe?"],
    },
  ],
  english1: [
    {
      prompt: "A paragraph argues that libraries should stay open later. Which revision would best strengthen the argument?",
      standard: "English I: Revising Argument",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Add data showing many students need evening study space", "Add a joke about books", "Remove the claim", "Use a less specific verb"],
      correct: 0,
      skill: "写作修订",
      explanation: "Relevant evidence strengthens an argument. Data about student need directly supports the claim about later library hours.",
      coachHints: ["What is the paragraph trying to prove?", "Which revision adds relevant support rather than decoration?"],
    },
    {
      prompt: "A story shifts from short, tense sentences during a storm to longer sentences after sunrise. What is the likely effect?",
      standard: "English I: Author's Craft",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The sentence structure mirrors a move from tension to calm", "The author stops developing mood", "The plot becomes impossible to follow", "The setting changes from fiction to nonfiction"],
      correct: 0,
      skill: "分析作者意图",
      explanation: "Sentence length and rhythm can shape mood. Short sentences can feel tense, while longer sentences can slow the pace.",
      coachHints: ["How do short sentences usually feel?", "What changes after sunrise in both mood and sentence style?"],
    },
    {
      prompt: "Which sentence best integrates evidence into an analysis paragraph?",
      standard: "English I: Text Evidence",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The narrator's 'shaking hands' reveal fear because the detail shows a physical reaction", "This quote is good", "The story has evidence somewhere", "Fear is a word"],
      correct: 0,
      skill: "引用文本证据",
      explanation: "Strong evidence integration names the detail and explains how it supports the inference.",
      coachHints: ["Which choice includes both evidence and explanation?", "Does the sentence explain why the quoted detail matters?"],
    },
    {
      prompt: "A student writes, 'The author makes the character sad.' Which revision makes the analysis stronger?",
      standard: "English I: Literary Analysis",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The author reveals sadness through the character's silence and repeated glances at the empty chair", "The author writes words", "The character is sad because I think so", "Sadness is a feeling"],
      correct: 0,
      skill: "引用文本证据",
      explanation: "Strong analysis connects a claim to specific textual evidence and explains how the evidence shows the idea.",
      coachHints: ["Where is the evidence in the sentence?", "Does the revision explain how the author shows sadness?"],
    },
    {
      prompt: "Which transition best connects a counterclaim to a rebuttal in an argumentative essay?",
      standard: "English I: Argument Writing",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Although some argue this policy is costly, the long-term savings outweigh the initial expense", "Also also also", "This is the end", "For example, blue is a color"],
      correct: 0,
      skill: "写作修订",
      explanation: "A rebuttal acknowledges the other side and then responds with reasoning that supports the writer's claim.",
      coachHints: ["Which choice admits the opposing point?", "Which choice answers that point instead of ignoring it?"],
    },
    {
      prompt: "In a passage, the narrator describes a trophy as 'heavier than it looked' after losing a friendship. What is the best interpretation?",
      standard: "English I: Symbolism and Theme",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The trophy symbolizes a victory that carries emotional cost", "The trophy is made of unusual metal only", "The narrator forgot how to lift objects", "The passage has no theme"],
      correct: 0,
      skill: "分析作者意图",
      explanation: "Objects can become symbols. The trophy's weight connects winning to the emotional burden of losing a friendship.",
      coachHints: ["Why mention the friendship loss with the trophy?", "Could 'heavier' mean emotional weight, not just physical weight?"],
    },
    {
      prompt: "A short response says, 'The author uses imagery.' Which revision best explains the effect of the imagery?",
      standard: "English I: Constructed Response",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The description of 'dust clinging to the windows' creates a neglected mood", "Imagery is in the story", "The author uses words", "Windows are objects"],
      correct: 0,
      skill: "分析作者意图",
      explanation: "A strong constructed response names the image and explains its effect on mood or meaning.",
      coachHints: ["Which words are the image?", "What mood does that image create?"],
    },
    {
      prompt: "Which thesis is strongest for an essay about whether schools should limit phone use?",
      standard: "English I: Argument Writing",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["Schools should limit phone use during class because it improves focus while still allowing emergency access", "Phones exist in schools", "Some people like phones and some do not", "This essay is about phones"],
      correct: 0,
      skill: "写作修订",
      explanation: "A strong thesis takes a clear position and gives a reason that can be developed with evidence.",
      coachHints: ["Which choice takes a clear side?", "Which choice gives a reason that can be supported?"],
    },
    {
      prompt: "A character smiles while saying, 'I'm perfectly fine,' after being betrayed. What inference should an analysis explain?",
      standard: "English I: Inference and Characterization",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The character may be hiding pain behind a calm appearance", "The character has no conflict", "The betrayal did not matter", "The smile proves complete happiness"],
      correct: 0,
      skill: "引用文本证据",
      explanation: "The contrast between betrayal and the calm statement suggests hidden emotion, not simple happiness.",
      coachHints: ["What conflict happened before the smile?", "Does the statement match the situation or contrast with it?"],
    },
  ],
  algebra1: [
    {
      prompt: "A gym charges a $40 joining fee and $18 per month. Which function gives the total cost C after m months?",
      standard: "Algebra I: Linear Function Modeling",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["C = 18m + 40", "C = 40m + 18", "C = 58m", "C = 18m - 40"],
      correct: 0,
      skill: "线性方程",
      explanation: "The one-time fee is the y-intercept, and the monthly cost is the rate multiplied by the number of months.",
      coachHints: ["Which cost happens only once?", "Which cost repeats each month?"],
    },
    {
      prompt: "The graph of y = (x - 3)^2 - 5 is compared with y = x^2. Which transformation occurred?",
      standard: "Algebra I: Quadratic Transformations",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Right 3 and down 5", "Left 3 and up 5", "Right 5 and down 3", "Left 5 and up 3"],
      correct: 0,
      skill: "函数图像",
      explanation: "In vertex form, (x - h)^2 + k moves the parabola right h and up k. Here h = 3 and k = -5.",
      coachHints: ["What does x - 3 do inside the square?", "What does -5 do outside the square?"],
    },
    {
      prompt: "A system has equations y = 2x + 1 and y = 2x - 4. What can be concluded without graphing?",
      standard: "Algebra I: Systems of Linear Equations",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The lines are parallel and have no solution", "The lines intersect at x = 0", "The equations are identical", "The system has infinitely many solutions"],
      correct: 0,
      skill: "线性方程",
      explanation: "The slopes are the same but the y-intercepts are different, so the lines are parallel and never intersect.",
      coachHints: ["Compare the slopes first.", "What happens when slopes match but intercepts differ?"],
    },
    {
      prompt: "A student solves 4(x - 3) = 28 by writing 4x - 3 = 28. What mistake did the student make?",
      standard: "Algebra I: Error Analysis with Distributive Property",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The student did not distribute 4 to both x and -3", "The student divided by 4 too early", "The student changed 28 into 3", "There is no mistake"],
      correct: 0,
      skill: "解一元一次方程",
      explanation: "The 4 multiplies the entire quantity x - 3, so it must multiply both terms: 4x - 12.",
      coachHints: ["What does the parenthesis mean?", "Which terms inside the parenthesis should 4 multiply?"],
    },
    {
      prompt: "The function f(x) = -2x + 9 models a line. What does the y-intercept mean in context if x is hours and f(x) is gallons left?",
      standard: "Algebra I: Function Interpretation",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["There were 9 gallons at the start", "The amount increases by 9 gallons per hour", "The tank is empty after 9 hours", "The rate is positive"],
      correct: 0,
      skill: "函数图像解释",
      explanation: "The y-intercept is the value when x = 0. At 0 hours, the model shows 9 gallons left.",
      coachHints: ["What does x = 0 mean in this context?", "Which number is not attached to x?"],
    },
    {
      prompt: "A parabola has vertex (4, -2) and opens down. Which statement is true?",
      standard: "Algebra I: Quadratic Features",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["The maximum value is -2", "The minimum value is -2", "The axis of symmetry is y = 4", "The graph opens up"],
      correct: 0,
      skill: "函数图像",
      explanation: "A downward-opening parabola has a maximum at its vertex. The y-value of the vertex is the maximum output.",
      coachHints: ["Does opening down create a maximum or minimum?", "Which coordinate gives the output value?"],
    },
    {
      prompt: "A student writes that the solution to 2x + 5 = 17 is x = 11. What explanation identifies the mistake?",
      standard: "Algebra I: Equation Error Analysis",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The student subtracted 5 but forgot to divide by 2", "The student should add 17 and 5", "The equation has no solution", "x must always equal 0"],
      correct: 0,
      skill: "解一元一次方程",
      explanation: "After subtracting 5, the equation becomes 2x = 12, so x must be 6.",
      coachHints: ["What inverse operation removes +5?", "What still needs to happen after 2x = 12?"],
    },
    {
      prompt: "A linear function has x-intercept 6 and y-intercept -3. What does the x-intercept mean?",
      standard: "Algebra I: Intercepts in Context",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The input value when the output is 0", "The output value when input is 0", "The slope of the graph", "The maximum value"],
      correct: 0,
      skill: "函数图像解释",
      explanation: "An x-intercept is where the graph crosses the x-axis, so the y-value or output is 0.",
      coachHints: ["What is y on the x-axis?", "Does x-intercept describe input or output?"],
    },
    {
      prompt: "A data set fits an exponential model better than a linear model. Which pattern would support that choice?",
      standard: "Algebra I: Function Families",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["The outputs multiply by a common factor for equal x-steps", "The outputs add the same amount each time", "The graph is always horizontal", "The x-values are all the same"],
      correct: 0,
      skill: "函数图像",
      explanation: "Exponential patterns involve repeated multiplication over equal intervals, while linear patterns involve repeated addition.",
      coachHints: ["Are the y-values adding or multiplying?", "Which function type uses a common ratio?"],
    },
  ],
  geometry: [
    {
      prompt: "A triangle has sides 7, 24, and 25. What conclusion is best supported?",
      standard: "Geometry: Right Triangles",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["It is a right triangle because 7^2 + 24^2 = 25^2", "It is equilateral", "It cannot form a triangle", "It has no longest side"],
      correct: 0,
      skill: "几何词汇",
      explanation: "The Pythagorean relationship holds because 49 + 576 = 625, so the triangle is right.",
      coachHints: ["Which side should be the hypotenuse?", "Check whether a^2 + b^2 equals c^2."],
    },
    {
      prompt: "Two triangles are similar with scale factor 3 from the smaller to the larger. If the smaller area is 12, what is the larger area?",
      standard: "Geometry: Similarity and Area",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["108", "36", "48", "15"],
      correct: 0,
      skill: "相似与比例",
      explanation: "Area changes by the square of the scale factor. Since 3^2 = 9, the larger area is 12 times 9.",
      coachHints: ["Does area scale by 3 or by 3 squared?", "What is 12 multiplied by 9?"],
    },
    {
      prompt: "In a proof, two angles are vertical angles. Which reason justifies that they are congruent?",
      standard: "Geometry: Proof Reasoning",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Vertical angles are congruent", "All angles are right angles", "Corresponding sides are proportional", "The triangles are similar"],
      correct: 0,
      skill: "证明书写",
      explanation: "Proofs require precise reasons. The theorem for opposite angles formed by intersecting lines is that vertical angles are congruent.",
      coachHints: ["What type of angle pair is named?", "Which theorem directly matches that pair?"],
    },
    {
      prompt: "A student claims two triangles are congruent because they have three matching angles. What is the issue with this reasoning?",
      standard: "Geometry: Similarity vs Congruence",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["AAA proves similarity, not necessarily congruence", "Three angles prove the triangles are circles", "Angles cannot be compared", "Congruence never uses angles"],
      correct: 0,
      skill: "全等判定",
      explanation: "Matching angles show the same shape, but side lengths could be different sizes. Congruence requires same shape and same size.",
      coachHints: ["What does AAA guarantee?", "What extra information is needed for congruence?"],
    },
    {
      prompt: "A dilation centered at the origin maps (3, -6) to (1, -2). What is the scale factor?",
      standard: "Geometry: Transformations",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["1/3", "3", "-3", "2"],
      correct: 0,
      skill: "相似与比例",
      explanation: "Each coordinate is multiplied by 1/3: 3 becomes 1 and -6 becomes -2.",
      coachHints: ["What number changes 3 into 1?", "Check whether the same number changes -6 into -2."],
    },
    {
      prompt: "A circle has radius 6. A student uses 2πr to find area. What mistake is being made?",
      standard: "Geometry: Area and Circumference",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["2πr is circumference, not area", "The radius should always be doubled first for area", "Area uses no formula", "The value of π is always 6"],
      correct: 0,
      skill: "几何词汇",
      explanation: "Circle area uses πr^2. The formula 2πr measures distance around the circle, which is circumference.",
      coachHints: ["What does 2πr measure?", "Which formula uses the radius squared?"],
    },
    {
      prompt: "A proof states that two triangles are congruent by HL. What information must be known?",
      standard: "Geometry: Right Triangle Congruence",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["Both triangles are right triangles with congruent hypotenuse and one leg", "All three angles are acute", "Only one angle is congruent", "The triangles are both large"],
      correct: 0,
      skill: "全等判定",
      explanation: "HL applies only to right triangles and requires a congruent hypotenuse and a congruent leg.",
      coachHints: ["What kind of triangles does HL apply to?", "What do H and L stand for?"],
    },
    {
      prompt: "A student says a rotation changes the size of a figure. Which correction is accurate?",
      standard: "Geometry: Transformations",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["A rotation preserves size and shape; it changes orientation", "A rotation always doubles side lengths", "A rotation changes only area", "A rotation makes figures unrelated"],
      correct: 0,
      skill: "几何词汇",
      explanation: "Rigid transformations such as rotations preserve distance and angle measure, so the figure stays congruent.",
      coachHints: ["Is rotation a rigid transformation?", "What changes: size, shape, or orientation?"],
    },
    {
      prompt: "Two similar polygons have side lengths in a 2:5 ratio. If the smaller perimeter is 18, what is the larger perimeter?",
      standard: "Geometry: Similarity and Perimeter",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["45", "36", "90", "7.2"],
      correct: 0,
      skill: "相似与比例",
      explanation: "Perimeter scales by the same factor as side lengths. From 2 to 5 is multiplying by 5/2, so 18 times 5/2 is 45.",
      coachHints: ["Does perimeter scale like length or area?", "What factor changes 2 parts into 5 parts?"],
    },
  ],
  biology: [
    {
      prompt: "A cell is placed in pure water and swells. Which explanation best connects the observation to cell transport?",
      standard: "Biology: Cell Transport",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Water moved into the cell by osmosis", "DNA left the nucleus", "The cell made glucose from light", "Protein synthesis stopped immediately"],
      correct: 0,
      skill: "细胞结构功能",
      explanation: "Osmosis is water movement across a membrane. In pure water, water can move into the cell and make it swell.",
      coachHints: ["What substance is moving?", "What process describes water crossing a membrane?"],
    },
    {
      prompt: "A pedigree shows two unaffected parents having an affected child. What inheritance pattern is most likely?",
      standard: "Biology: Genetics",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Recessive inheritance", "The trait cannot be inherited", "Both parents must show the trait", "The child has no alleles"],
      correct: 0,
      skill: "遗传基础",
      explanation: "Two unaffected carriers can have a child with a recessive trait if the child inherits the recessive allele from both parents.",
      coachHints: ["Can a parent carry a recessive allele without showing it?", "What must the child inherit to show a recessive trait?"],
    },
    {
      prompt: "A graph shows photosynthesis rate rising with light intensity, then leveling off. Which explanation is best?",
      standard: "Biology: Photosynthesis and Limiting Factors",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch",
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Another factor becomes limiting after light is no longer the main limit", "Light stops being energy", "Photosynthesis becomes impossible", "The graph proves plants do not need carbon dioxide"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "When a rate levels off, increasing one factor no longer increases the process because another factor limits the rate.",
      coachHints: ["What does leveling off mean on a graph?", "If more light no longer helps, what might be limiting the process?"],
    },
    {
      prompt: "A student says mitochondria make energy from sunlight. What correction is most accurate?",
      standard: "Biology: Cell Energy",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Chloroplasts capture light energy; mitochondria release usable energy from food molecules", "Mitochondria are only found in bacteria", "Chloroplasts make DNA only", "Cells do not transform energy"],
      correct: 0,
      skill: "能量转化",
      explanation: "Photosynthesis occurs in chloroplasts, while mitochondria are involved in cellular respiration and ATP production.",
      coachHints: ["Which organelle is linked to photosynthesis?", "Which process is linked to mitochondria?"],
    },
    {
      prompt: "In a food web, a toxin becomes more concentrated in top predators. Which concept explains this pattern?",
      standard: "Biology: Ecology",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Biomagnification", "Osmosis", "Mitosis", "Natural selection only"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "Biomagnification occurs when toxins build up at higher trophic levels as predators consume many contaminated organisms.",
      coachHints: ["Which organisms eat many others in a food web?", "What happens to a toxin as it moves up trophic levels?"],
    },
    {
      prompt: "A DNA sequence changes, but the resulting protein has the same amino acid sequence. What is the best explanation?",
      standard: "Biology: Genetics and Protein Synthesis",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 2",
      multiStepReasoning: true,
      openResponse: true,
      errorAnalysis: true,
      answers: ["Different codons can code for the same amino acid", "DNA does not affect proteins", "All mutations destroy cells", "Amino acids are never coded by DNA"],
      correct: 0,
      skill: "遗传基础",
      explanation: "The genetic code has redundancy, so some DNA changes do not change the amino acid sequence.",
      coachHints: ["Can more than one codon match the same amino acid?", "Would every DNA base change necessarily change the protein?"],
    },
    {
      prompt: "A student claims enzymes are used up during reactions because the reaction slows later. Which correction is best?",
      standard: "Biology: Enzymes",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["Enzymes are catalysts and are not consumed, but conditions or substrate amount can affect rate", "Enzymes are always destroyed after one reaction", "Enzymes are the same as DNA", "Reaction rate never changes"],
      correct: 0,
      skill: "能量转化",
      explanation: "Enzymes lower activation energy and can be reused. A slowing reaction may involve temperature, pH, or substrate changes.",
      coachHints: ["What is a catalyst?", "What factors besides enzyme amount can change reaction rate?"],
    },
    {
      prompt: "A cell with 24 chromosomes divides by meiosis. What should a student explain about the resulting sex cells?",
      standard: "Biology: Cell Division",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["They have 12 chromosomes because meiosis halves the chromosome number", "They have 48 chromosomes because meiosis doubles DNA forever", "They have no genetic material", "They are identical to body cells in chromosome number"],
      correct: 0,
      skill: "遗传基础",
      explanation: "Meiosis produces gametes with half the chromosome number, so fertilization can restore the full number.",
      coachHints: ["Does meiosis make body cells or sex cells?", "What happens to chromosome number in gametes?"],
    },
    {
      prompt: "A graph shows a predator population rising shortly after a prey population rises. What explanation best fits the pattern?",
      standard: "Biology: Ecology Data Analysis",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 3",
      multiStepReasoning: true,
      openResponse: true,
      constructedResponse: true,
      answers: ["More prey can support more predators after a time lag", "Predators create sunlight", "Prey do not affect ecosystems", "The populations must be unrelated"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "Predator populations often respond after prey populations change because food availability affects survival and reproduction.",
      coachHints: ["What food source increased first?", "Why might predator numbers change after, not before, prey numbers?"],
    },
  ],
};

const twoHourExpansionBatch4 = {
  math8: [
    {
      prompt: "A student first solves 2x + 3 = 15, then checks the answer in a proportional graph. Which habit is being practiced?",
      standard: "Grade 8 Math: Spiral Review Equations and Graphs",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Connecting algebraic solving with graph interpretation", "Ignoring the equation after graphing", "Changing the answer to fit the graph", "Using only estimation"],
      correct: 0,
      skill: "多步文字题",
      explanation: "Spiral review asks students to connect earlier equation skills with graph reasoning instead of treating topics separately.",
      coachHints: ["What skill solves the equation?", "What second skill checks whether the answer makes sense on a graph?"],
    },
    {
      prompt: "A line has equation y = -4x + 10. Which statement reviews both slope and intercept?",
      standard: "Grade 8 Math: Linear Functions Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The graph starts at 10 on the y-axis and decreases 4 for each 1 increase in x", "The graph starts at -4 and increases by 10", "The graph is proportional", "The graph has no y-intercept"],
      correct: 0,
      skill: "斜率概念",
      explanation: "The equation y = mx + b shows slope m and y-intercept b. Here m is -4 and b is 10.",
      coachHints: ["Which number is attached to x?", "Which number is the starting value when x is 0?"],
    },
    {
      prompt: "A student compares two plans: Plan A is $12 plus $3 per hour, Plan B is $6 per hour. What should be done first?",
      standard: "Grade 8 Math: Systems from Context",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Write a cost expression for each plan", "Choose Plan A because it has a fixed fee", "Ignore the hourly rates", "Multiply all numbers together"],
      correct: 0,
      skill: "比例关系",
      explanation: "Comparing plans requires modeling each total cost before solving or judging which is cheaper.",
      coachHints: ["What expression represents Plan A?", "What expression represents Plan B?"],
    },
  ],
  rla8: [
    {
      prompt: "A student identifies a theme but uses evidence from only one paragraph. What should the student do to strengthen the response?",
      standard: "Grade 8 RLA: Spiral Review Theme and Evidence",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Use evidence from across the text to show the theme develops", "Delete the theme", "Only quote the title", "Use a longer sentence without evidence"],
      correct: 0,
      skill: "主题与主张",
      explanation: "A theme usually develops across the text, so strong evidence should show more than one isolated moment.",
      coachHints: ["Does the evidence show the whole text or one moment?", "What later detail confirms the same theme?"],
    },
    {
      prompt: "Two passages use the word 'bright': one about sunlight, one about a student's idea. What skill is being reviewed?",
      standard: "Grade 8 RLA: Vocabulary in Context",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Using context to choose the meaning of a word", "Counting how many letters are in a word", "Assuming every word has one meaning", "Skipping surrounding sentences"],
      correct: 0,
      skill: "词汇语境",
      explanation: "The same word can have different meanings. Context tells whether 'bright' means light or intelligent.",
      coachHints: ["What does bright describe in each passage?", "Do the surrounding words point to light or thinking?"],
    },
    {
      prompt: "A paired-text response says both authors disagree, but both actually support the same policy for different reasons. What is the mistake?",
      standard: "Grade 8 RLA: Paired Text Spiral Review",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The student confused different reasons with different positions", "The texts cannot share a claim", "Reasons never matter", "The response needs fewer details"],
      correct: 0,
      skill: "证据比较",
      explanation: "Authors can agree on a claim while supporting it with different evidence or reasoning.",
      coachHints: ["What position does each author take?", "Are the reasons different even if the claim is similar?"],
    },
  ],
  science8: [
    {
      prompt: "A student uses a data table from a density lab to explain why an object sinks. Which concepts are being connected?",
      standard: "Grade 8 Science: Spiral Review Data and Density",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Data interpretation, density, and evidence-based reasoning", "Weather and genetics", "Only vocabulary memorization", "Moon phases and seasons"],
      correct: 0,
      skill: "数据解释",
      explanation: "A strong science explanation uses the data, the density concept, and reasoning that connects evidence to the claim.",
      coachHints: ["What data value supports the claim?", "How does density explain sinking or floating?"],
    },
    {
      prompt: "A model shows convection currents and a student connects it to plate motion. What should the explanation include?",
      standard: "Grade 8 Science: Earth Science Spiral Review",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["How heat-driven movement in the mantle can help move plates", "Why plates never move", "Why heat has no effect on materials", "Only the names of the continents"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "Convection links heat transfer to material movement, which helps explain plate motion in Earth systems.",
      coachHints: ["What causes the current to move?", "How could moving mantle material affect plates?"],
    },
    {
      prompt: "An experiment question asks for the independent variable, dependent variable, and control. What kind of review is this?",
      standard: "Grade 8 Science: Investigation Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Experimental design review", "Only graph reading", "Only astronomy", "A vocabulary-free question"],
      correct: 0,
      skill: "实验设计",
      explanation: "Identifying variables and controls is core experimental design, and it supports judging whether a conclusion is valid.",
      coachHints: ["What is changed on purpose?", "What is measured and what is kept the same?"],
    },
  ],
  english1: [
    {
      prompt: "A student revises a literary analysis by adding a quote and one sentence explaining how the quote supports the claim. What skill is being strengthened?",
      standard: "English I: Spiral Review Evidence Integration",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Integrating evidence with analysis", "Making the paragraph shorter only", "Avoiding the claim", "Replacing evidence with opinion"],
      correct: 0,
      skill: "引用文本证据",
      explanation: "Evidence must be connected to the claim through analysis, not simply dropped into the paragraph.",
      coachHints: ["Where is the quote?", "Where does the writer explain why it matters?"],
    },
    {
      prompt: "An argument essay includes a claim, a counterclaim, and a rebuttal. What should the rebuttal do?",
      standard: "English I: Argument Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Respond to the counterclaim with reasoning or evidence", "Repeat the title", "Ignore the other side", "End the essay immediately"],
      correct: 0,
      skill: "写作修订",
      explanation: "A rebuttal strengthens an argument by answering the opposing view rather than pretending it does not exist.",
      coachHints: ["What opposing point was raised?", "What evidence or reasoning answers it?"],
    },
    {
      prompt: "A passage uses weather changes to mirror a character's emotional shift. What should the analysis explain?",
      standard: "English I: Author's Craft Spiral Review",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["How setting details reflect the character's internal change", "Why weather reports are nonfiction", "Why characters cannot change", "How to remove all imagery"],
      correct: 0,
      skill: "分析作者意图",
      explanation: "Authors often use setting as a mirror for mood or character development, so analysis should connect external details to internal change.",
      coachHints: ["What changes in the weather?", "What changes inside the character at the same time?"],
    },
  ],
  algebra1: [
    {
      prompt: "A student solves a linear equation, then checks the solution by substituting it back. What review habit is this?",
      standard: "Algebra I: Spiral Review Equations",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Verifying a solution", "Changing the equation", "Estimating without checking", "Graphing only the y-intercept"],
      correct: 0,
      skill: "解一元一次方程",
      explanation: "Substitution checks whether the proposed value makes the original equation true.",
      coachHints: ["Where should the solution be substituted?", "What should both sides equal if the solution is correct?"],
    },
    {
      prompt: "A table has outputs that add 7 for each increase of 1 in x. What linear feature is being reviewed?",
      standard: "Algebra I: Linear Function Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Slope or constant rate of change", "Quadratic vertex", "Exponential decay only", "No relationship"],
      correct: 0,
      skill: "斜率与变化率",
      explanation: "A constant additive change in outputs over equal input steps is the slope of a linear function.",
      coachHints: ["How much does y change each step?", "Is the change constant?"],
    },
    {
      prompt: "A quadratic word problem asks when a ball hits the ground. Which feature should a student look for?",
      standard: "Algebra I: Quadratic Spiral Review",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The positive x-intercept where height equals 0", "The y-intercept only", "The slope of a line", "The largest coefficient"],
      correct: 0,
      skill: "函数图像",
      explanation: "When the ball hits the ground, height is 0, so the meaningful solution is the positive x-intercept.",
      coachHints: ["What does height equal on the ground?", "Which intercept has output 0?"],
    },
  ],
  geometry: [
    {
      prompt: "A problem combines parallel-line angles with triangle angle sum. What should be found first?",
      standard: "Geometry: Spiral Review Angle Relationships",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Use the parallel-line relationship to find a missing angle", "Assume all angles are 60 degrees", "Find area before angles", "Ignore the diagram markings"],
      correct: 0,
      skill: "角度关系",
      explanation: "Multi-step geometry often starts with the angle relationship given by parallel lines, then uses triangle angle sum.",
      coachHints: ["Which angles are marked by the parallel lines?", "What triangle fact can be used after that?"],
    },
    {
      prompt: "A student uses side ratio 2:3 to compare areas of similar figures. What must the student remember?",
      standard: "Geometry: Similarity Spiral Review",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Area ratio is the square of the side ratio", "Area ratio is always 2:3", "Similar figures have equal areas", "Ratios cannot be used for area"],
      correct: 0,
      skill: "相似与比例",
      explanation: "Lengths scale by the side ratio, while areas scale by the square of the side ratio.",
      coachHints: ["Does area measure one dimension or two?", "What happens when both dimensions scale?"],
    },
    {
      prompt: "A proof step says two segments are congruent because a midpoint divides a segment. What reason should be written?",
      standard: "Geometry: Proof Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Definition of midpoint", "Vertical angles are congruent", "Pythagorean theorem", "Area formula"],
      correct: 0,
      skill: "证明书写",
      explanation: "A midpoint divides a segment into two congruent parts by definition.",
      coachHints: ["What does midpoint mean?", "Which reason directly matches that definition?"],
    },
  ],
  biology: [
    {
      prompt: "A question connects DNA, mRNA, and amino acids. Which process chain is being reviewed?",
      standard: "Biology: Protein Synthesis Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["Transcription and translation", "Osmosis and diffusion only", "Photosynthesis only", "Mitosis without DNA"],
      correct: 0,
      skill: "遗传基础",
      explanation: "Protein synthesis moves from DNA information to mRNA and then to an amino acid sequence.",
      coachHints: ["What molecule is made from DNA first?", "What is built from amino acids?"],
    },
    {
      prompt: "A model asks students to compare photosynthesis and cellular respiration. What relationship should be explained?",
      standard: "Biology: Energy Processes Spiral Review",
      difficulty: "进阶",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["They transform energy and use some of each other's products", "They are exactly the same process", "Only animals do both processes", "Neither process involves molecules"],
      correct: 0,
      skill: "能量转化",
      explanation: "Photosynthesis stores energy in glucose, while cellular respiration releases usable energy from glucose.",
      coachHints: ["What does photosynthesis produce?", "What does respiration use to release energy?"],
    },
    {
      prompt: "A graph shows enzyme activity at different pH levels. What should a student identify before choosing a conclusion?",
      standard: "Biology: Enzyme Data Spiral Review",
      difficulty: "挑战",
      sourceBatch: "STAAR-style original batch 4",
      spiralReview: true,
      multiStepReasoning: true,
      openResponse: true,
      answers: ["The pH where enzyme activity is highest", "The longest label on the graph", "The color of the curve", "A conclusion unrelated to the data"],
      correct: 0,
      skill: "科学图表分析",
      explanation: "A data-based conclusion should begin with the highest or lowest activity shown by the graph and connect it to enzyme function.",
      coachHints: ["Where is the graph's peak?", "What does the peak tell you about enzyme conditions?"],
    },
  ],
};

Object.entries(twoHourExpansionBatch4).forEach(([subjectId, questions]) => {
  window.twoHourExpansionQuestionBank[subjectId] = (window.twoHourExpansionQuestionBank[subjectId] || []).concat(questions);
});

const systematicExpansionBlueprints = {
  math8: {
    standard: "Grade 8 Math: STAAR-style Original Practice",
    skillCycle: ["斜率概念", "多步文字题", "比例关系", "数据图表", "方程建模", "函数关系"],
    stems: [
      "A gym charges a fixed sign-up fee and a monthly fee. Which expression represents the total cost after n months?",
      "A table shows x increasing by 2 while y increases by 7. What should the student compare first?",
      "A recipe uses 3 cups of flour for 8 servings. What question checks whether a student understands the unit rate?",
      "A graph shows a line crossing the y-axis above zero and rising. What can a student conclude before calculating?",
      "A student solves an inequality but forgets to include the fixed starting amount. What is the likely mistake?",
      "A scatterplot has a clear downward trend with a few points not on the trend line. Which interpretation is most careful?",
    ],
    corrects: [
      "fixed fee + monthly fee times n",
      "change in y divided by change in x",
      "how much flour is needed for one serving",
      "the relationship has a positive rate and a positive starting value",
      "the model is missing the initial value",
      "there is a negative association, but predictions are estimates",
    ],
    explanation: "This question asks students to identify structure before calculating, which is expected in school-level multi-step math practice.",
    mistake: "Students often choose an operation from the numbers without naming the relationship first.",
  },
  rla8: {
    standard: "Grade 8 RLA: STAAR-style Original Practice",
    skillCycle: ["中心思想", "文本证据", "推断", "词汇语境", "作者目的", "细节支持"],
    stems: [
      "A paragraph begins with a claim and then gives two examples. What should a student identify first?",
      "A question asks which sentence best supports an inference. What should the student look for?",
      "A character changes their decision after hearing new information. What does this most likely show?",
      "A word has a familiar meaning, but the sentence uses it differently. What is the best first step?",
      "An author includes a statistic after a personal story. Why might the author do this?",
      "Two details point to the same conclusion, but one answer choice only repeats a detail. What is the issue?",
    ],
    corrects: [
      "the central claim and how the examples support it",
      "a detail that directly proves the inference",
      "the character's motivation has changed",
      "use surrounding words to infer the meaning",
      "to support the point with evidence",
      "the answer needs to explain the idea, not only repeat evidence",
    ],
    explanation: "Reading questions require students to connect claim, evidence, and inference rather than choosing familiar words.",
    mistake: "Students often pick a true detail that does not answer the exact question.",
  },
  science8: {
    standard: "Grade 8 Science: STAAR-style Original Practice",
    skillCycle: ["变量识别", "科学图表", "生态系统", "力和运动", "实验设计", "证据推理"],
    stems: [
      "A lab changes the amount of light and measures plant growth. What is the independent variable?",
      "A graph shows temperature rising while solubility also rises. What should a student describe first?",
      "A food web loses one predator. What should a student trace before predicting the effect?",
      "A cart moves farther when a stronger push is used. Which relationship is being tested?",
      "A student wants a fair test with two groups. What must stay the same?",
      "A conclusion is written without mentioning data. What is missing?",
    ],
    corrects: [
      "the amount of light",
      "the pattern between temperature and solubility",
      "how energy and population relationships change",
      "force and motion",
      "controlled variables",
      "evidence from the investigation",
    ],
    explanation: "Science questions should be answered by identifying variables, patterns, and evidence before choosing a claim.",
    mistake: "Students often describe the topic but forget to connect it to measured evidence.",
  },
  english1: {
    standard: "English I: STAAR EOC-style Original Practice",
    skillCycle: ["识别中心观点", "引用文本证据", "分析作者意图", "写作修订", "推断", "论证结构"],
    stems: [
      "An author opens with a problem and ends with a call to action. What should a student identify first?",
      "A question asks which evidence best supports a claim about school policy. What makes evidence strong?",
      "A paragraph includes a counterargument. Why might the writer include it?",
      "A sentence is wordy and repeats the same idea twice. What revision is best?",
      "An answer choice sounds reasonable but is not stated or supported. What is the problem?",
      "A short response has a claim and quote but no explanation. What is missing?",
    ],
    corrects: [
      "the author's central position",
      "it directly connects to the claim",
      "to respond to an opposing view",
      "combine the repeated idea into a clearer sentence",
      "it is not supported by the text",
      "the reasoning that explains how the evidence proves the claim",
    ],
    explanation: "English I questions expect students to connect claim, evidence, and reasoning, especially in EOC-style reading and writing tasks.",
    mistake: "Students often quote evidence but skip the explanation that connects it to the claim.",
  },
  algebra1: {
    standard: "Algebra I: STAAR EOC-style Original Practice",
    skillCycle: ["斜率与变化率", "线性方程建模", "解一元一次方程", "函数图像解释", "不等式", "系统建模"],
    stems: [
      "A phone plan has a base fee and a charge per gigabyte. Which part is the y-intercept?",
      "A line passes through two points. What does a student calculate before writing y = mx + b?",
      "A student solves 5x - 9 = 26 but adds 9 to only one side. What rule is broken?",
      "A graph crosses the x-axis at 4. What does that point represent in context?",
      "A word problem says the cost must be at most 60 dollars. Which inequality symbol fits?",
      "Two plans have equal cost at one point. What does the intersection represent?",
    ],
    corrects: [
      "the base fee",
      "the slope",
      "the same operation must be done to both sides",
      "the input where the output is zero",
      "less than or equal to",
      "the input where both plans cost the same",
    ],
    explanation: "Algebra I practice should connect equations, graphs, and context before focusing on calculation.",
    mistake: "Students often manipulate symbols without naming what each part means.",
  },
  geometry: {
    standard: "Geometry: TEKS-style Original Practice",
    skillCycle: ["全等判定", "角关系", "证明书写", "几何词汇", "相似三角形", "圆和面积"],
    stems: [
      "Two triangles have two pairs of equal angles. What can be concluded first?",
      "Parallel lines are cut by a transversal. Which angle relationship should be checked?",
      "A proof lists statements but no reasons. What is incomplete?",
      "A student confuses radius and diameter in a circle problem. What should be identified first?",
      "Two triangles have proportional sides. What relationship may apply?",
      "A composite figure combines a rectangle and semicircle. What should a student do first?",
    ],
    corrects: [
      "the triangles may be similar by angle-angle",
      "corresponding or alternate interior angles",
      "the reasons that justify each statement",
      "which segment goes from center to edge",
      "triangle similarity",
      "split the figure into known shapes",
    ],
    explanation: "Geometry questions require students to name relationships and justify steps, not only calculate a number.",
    mistake: "Students often jump to a formula before identifying the figure relationship.",
  },
  biology: {
    standard: "Biology: STAAR EOC-style Original Practice",
    skillCycle: ["细胞结构功能", "能量转化", "遗传基础", "生态系统关系", "科学图表分析", "稳态"],
    stems: [
      "A cell needs more ATP for active transport. Which process should a student connect to this need?",
      "A model compares photosynthesis and respiration. What relationship should be described?",
      "A Punnett square shows two heterozygous parents. What does it predict?",
      "A population decreases after its food source declines. What should be traced first?",
      "A graph shows enzyme activity changing with temperature. What feature matters most?",
      "The body sweats when temperature rises. Which concept does this show?",
    ],
    corrects: [
      "cellular respiration",
      "one process stores energy and the other releases usable energy",
      "probable offspring genotypes or traits",
      "energy flow and resource availability",
      "the temperature where activity is highest",
      "homeostasis",
    ],
    explanation: "Biology questions should connect structures, processes, and data patterns to the scientific claim.",
    mistake: "Students often memorize terms without explaining the process or evidence behind them.",
  },
};

function buildSystematicExpansionQuestions(subjectId, blueprint) {
  const difficulties = ["中等", "进阶", "挑战", "进阶", "挑战"];
  return Array.from({ length: 40 }, (_, index) => {
    const patternIndex = index % blueprint.stems.length;
    const cycle = Math.floor(index / blueprint.stems.length) + 1;
    const skill = blueprint.skillCycle[index % blueprint.skillCycle.length];
    const difficulty = difficulties[index % difficulties.length];
    const schoolLevelDepth = index % 2 === 0 || difficulty === "挑战" || cycle >= 4;
    return {
      prompt: `${blueprint.stems[patternIndex]} (Systematic practice ${cycle}.${patternIndex + 1})`,
      standard: blueprint.standard,
      difficulty,
      sourceBatch: cycle >= 4 ? "systematic original expansion v2" : "systematic original expansion v1",
      structuredBank: true,
      schoolExamDepth: schoolLevelDepth ? `${subjectId} ${skill} school-level reasoning` : "",
      multiStepReasoning: schoolLevelDepth,
      openResponse: index % 3 !== 1 || cycle >= 4,
      errorAnalysis: index % 3 === 0 || cycle >= 4,
      constructedResponse: difficulty === "挑战" || index % 4 === 0 || cycle >= 5,
      answers: [
        blueprint.corrects[patternIndex],
        "choose the longest answer without checking the question",
        "ignore the context and use any familiar formula",
        "skip the evidence and guess from keywords",
      ],
      correct: 0,
      skill,
      explanation: `${blueprint.explanation} Focus skill: ${skill}.`,
      commonMistakes: [blueprint.mistake, "Guessing from keywords instead of explaining the first step."],
      aiHintLevel1: "先看小讲解：这类题先判断题目目标和第一步线索，不要先选答案。",
      aiHintLevel2: "只补一个空：我第一步先看____。",
      aiHintLevel3: "再把方法接完整：我第一步先____，因为____。",
      coachHints: [
        "先看一个老师示范句，再补题目里的关键词。",
        "只补第一步线索：我第一步先看____。",
      ],
    };
  });
}

Object.entries(systematicExpansionBlueprints).forEach(([subjectId, blueprint]) => {
  window.twoHourExpansionQuestionBank[subjectId] = (window.twoHourExpansionQuestionBank[subjectId] || []).concat(
    buildSystematicExpansionQuestions(subjectId, blueprint)
  );
});
